name: Loja-PHP Workflow

on:
  push:
    branches:
      - develop

jobs:
  build:
    name: Loja Laravel Workflow
    runs-on: ubuntu-latest
    steps:
      # Esta ação faz o check-out de seu repositório em $GITHUB_WORKSPACE, para que seu fluxo de trabalho possa acessá-lo.
      - uses: actions/checkout@v2

      # Instalação do Composer
      - uses: ./.github/actions/composer

      # Instalação do Laravel
      - uses: ./.github/actions/config-laravel

      # Execução dos testes
      - run: ./vendor/bin/phpunit
